<?php

namespace AppBundle\Repository;

/**
 * CartesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    {
        return $this->createQueryBuilder('c')
            ->indexBy('c','c.id')
            ->getQuery()
            ->getResult();
    }
}
