imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
            # other form themes
            - 'VichUploaderBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"


    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: AppBundle\Entity\User

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    encryption: "%mailer_encryption%"
    auth_mode: "%mailer_auth_mode%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
            address:        frenchfoodcontest@corentincloss.fr
            sender_name:    oui
    registration:
        form:
            type: AppBundle\Form\RegistrationType

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr

    mappings:
            avatar_image:
                uri_prefix:         /images/avatars
                upload_destination: '%kernel.root_dir%/../web/images/avatars'
                namer:              vich_uploader.namer_uniqid
                inject_on_load:     false
                delete_on_update:   false
                delete_on_remove:   true

            carte_image:
                uri_prefix:         /images/cartes
                upload_destination: '%kernel.root_dir%/../web/images/cartes'
                namer:              vich_uploader.namer_uniqid
                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true

            rang_image:
                uri_prefix:         /images/rangs
                upload_destination: '%kernel.root_dir%/../web/images/rangs'
                namer:              vich_uploader.namer_uniqid
                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true


fos_message:
    db_driver: orm
    thread_class: AppBundle\Entity\Thread
    message_class: AppBundle\Entity\Message

easy_admin:
    site_name: 'FFC - Admin'
    design:
        brand_color: '#0A7840'
    entities:
        User:
            class: AppBundle\Entity\User
            label: 'Users'
            export_path: '%kernel.root_dir/../var/export/user'
            password_encoding: { algorithm: 'bcrypt', cost: 12 }
            list:
                actions:
                    - { name: 'show', icon: 'search', label: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
                    - { name: 'delete', icon: 'times', label: 'Delete' }
                title: "User's list"
                fields:
                    - 'id'
                    - 'username'
                    - 'email'
                    - 'enabled'
                    - { property: 'last_login', type: 'datetime' }
                    - 'parties_gagnees'
                    - 'parties_perdues'
                    - 'points'
            show:
                title: 'User : (%%entity_id%%)'

            form:
                fields:
                    - 'username'
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - 'email'
                    - 'nom'
                    - 'prenom'
                    - 'birthday'
                    - 'enabled'
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_MODERATOR': 'ROLE_MODERATOR', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'sexe', type: 'choice', type_options: { multiple: false, choices: {'Homme': 'homme', 'Femme': 'femme'} } }
                    - { property: 'parties_gagnees', type_options: { required: false }}
                    - { property: 'parties_perdues', type_options: { required: false }}
                    - { property: 'points', type_options: { required: false }}
        Cartes:
            class: AppBundle\Entity\Cartes
            label: 'Cartes'
            list:
                actions:
                    - { name: 'show', icon: 'search', label: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
                    - { name: 'delete', icon: 'times', label: 'Delete' }
                title: "Cards' list"
                fields:
                    - 'id'
                    - 'categorie'
                    - 'nom'
                    - 'valeur'
                    - 'extra'
            form:
                fields:
                    - { property: 'categorie', type: 'choice', type_options: { multiple: false, choices: { 'Apéritif': 'aperitif', 'Entrée': 'entree', 'Plat': 'plat', 'Laitage': 'laitage', 'Dessert': 'dessert' } } }
                    - 'nom'
                    - { property: 'valeur', type: 'integer'}
                    - { property: 'imageFile', type: 'vich_image' }
                    - 'extra'
        Category:
            class: Discutea\DForumBundle\Entity\Category
            form:
                fields:
                    - 'name'
        Forum:
            class: Discutea\DForumBundle\Entity\Forum
            form:
                fields:
                    - 'name'
                    - 'description'
                    - 'position'
                    - 'category'
        Parties:
            class: AppBundle\Entity\Partie
            label: 'Liste des parties'
            list:
                actions:
                  - { name: 'show', icon: 'search', label: 'Show' }
                  - { name: 'edit', icon: 'pencil', label: 'Edit' }
                  - { name: 'delete', icon: 'times', label: 'Delete' }
        Rang:
            class: AppBundle\Entity\Rang
            lable: 'Rangs'
            list:
                actions:
                    - { name: 'show', icon: 'search', label: 'Voir' }
                    - { name: 'edit', icon: 'pencil', label: 'Modifier' }
                    - { name: 'delete', icon: 'times', label: 'Supprimer' }
            form:
                fields:
                    - { property: 'nom_rang', type: 'text'}
                    - { property: 'points_debut', type: 'integer'}
                    - { property: 'points_fin', type: 'integer'}
                    - 'role'
                    - { property: 'imageFile', type: 'vich_image' }


# Stof Doctrine Extensions
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

# Configurer knp paginator attention changer bien le page_name
knp_paginator:
    page_range: 3
    default_options:
        page_name: p
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

# Configuration discutea forum
discutea_forum:
    preview:
        enabled: true
    knp_paginator:
        page_name: p  #voir knp_paginator.default_option.page_name
        topics:
            enabled: true
            per_page: 10
        posts:
            enabled: true
            per_page: 10